# Stage 1: Build the frontend
FROM node:20-alpine as frontend-builder

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
RUN yarn build

# Stage 2: Frontend production image
FROM nginx:alpine as frontend
COPY --from=frontend-builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3030
CMD ["nginx", "-g", "daemon off;"]
